### PR TITLE
Improving TimeZone config

### PR DESCRIPTION
**Pull request by gabrielmccoll**
- defaults the timezone to the same as your Host timezone. 
- parameter to input timezone otherwise. 
- if no timezone section in .psd1 , just ignores. 

Did try to get a straight edit into the nested hashtables but I kind of suck so didn't manage it.

### CODE REVIEW

**Comment by jdhitsolutions** [comment]
I appreciate your work and willingness to contribute. I'm going to not accept this into the code base only because I am working on a larger toolset to make it easier to customize the psd1 files. In addition to changing the time zone, you might need to change a VM name to avoid a naming collision. Or you might want a different subnet or default password. I'm working on a broader tool to modify data configuration files.

**Comment by gabrielmccoll** [comment]
Dang !, this was my first go at contributing to an actual project with code.   
Not trying to have a go but was there somewhere I could have picked up on the fact this wasn't needed.  Not sure of the process, I just seen an open issue I thought I could grab.

**Comment by jdhitsolutions** [comment]
And I truly appreciate it. The challenge with the project is that any change has to be tested across all the configurations.

**Comment by gabrielmccoll** [comment]
V true, well let me know if I can help out with other stuff.   I'm a huge fan of lowering barriers of entry and also quickly making test infra to play with so this project is right up my alley.

**Pull request closed without merging**
